### ISSUE TITLE
Unify lens naming schemes

### ISSUE THREAD

**Issue by travitch** [travitch/surveyor#24]
Some lenses are prefixed with a `l`, while others are suffixed with a `L`.  It would be really nice to use a single naming scheme.

**Comment by vikraman** [comment]
I see that `TemplateHaskell` is already being used, so is there a reason not to do this with `makeLenses`?

**Comment by travitch** [comment]
I have an aspiration to try to just make lenses for the pieces of state that need it (and no more). I suppose the TH-based generators have some configurability, so that could be an option.
