### ISSUE TITLE
Issues with logging and handling errors

### ISSUE THREAD

**Issue by vikraman** [travitch/surveyor#36]
It looks like most error events are being handled, some in surveyor-core, some in surveyor-brick, but they are not getting logged in the UI, or in the log file. I can't figure out yet if something is not connected somewhere. 

This should also fix #13 since the llvm loader raises the appropriate event when the bitcode parser fails but it's not getting logged.

**Comment by travitch** [comment]
Is there a difference in behavior if you load via the built-in command after the TUI has started vs if you provide an input filename on the command line?  I'm noticing that the asynchronous loader is started before the TUI starts reading from the event channel. I would think that shouldn't matter, as the TUI ought to just read buffered messages.

**Comment by vikraman** [comment]
The behaviour is the same, it looks like the logger doesn't get initialised until you successfully load a file. So if you load a `.ll` file (which goes to the ELF loader), the loader returns an error but it doesn't get logged. But, if you load a proper `.bc` file first, then try to load a `.ll` file, you do see the error log. 

If you set the log file path before loading anything, then things are logged to the file and there are no issues.

**Comment by travitch** [comment]
I think we figured this out - until you load a file, the `appDraw` function only renders an unhelpful "help" message.  We should change `appDraw` to render the logs instead (and maybe just make that unhelpful help text the first log message).
