### ISSUE TITLE
Enable logging to a file by default

### ISSUE THREAD

**Issue by travitch** [travitch/surveyor#37]
The default right now is to just log to the internal buffer, which is a bit inconvenient when things actually go wrong.

**Comment by vikraman** [comment]
After #36 this seems less useful to have by default, setting up the file logger also requires starting an async task which is heavy(?).

**Comment by travitch** [comment]
It is very lightweight and I'm not concerned at all by the resource usage there.  It would probably at least be useful to have it for development.  I don't see any reason to disable it in the short term.
